# Generated by Django 5.0.2 on 2024-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('next_episode_count', models.IntegerField(blank=True, max_length=4, null=True)),
                ('total_episodes', models.IntegerField(blank=True, max_length=4, null=True)),
                ('release_date_next_ep', models.CharField(blank=True, max_length=100, null=True)),
                ('mediatype', models.CharField(blank=True, max_length=10, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('episode_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
