# Generated by Django 5.0.2 on 2024-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_remove_anime_user_favoriteanime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='next_episode_count',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
