# Generated by Django 5.0.3 on 2024-07-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_anime_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='pic_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
