# Generated by Django 5.0.2 on 2024-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_delete_favoriteanime'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorite_anime',
            field=models.ManyToManyField(null=True, to='anime.anime'),
        ),
    ]
