# Generated by Django 5.0.2 on 2024-04-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_myuser_favorite_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='favorite_anime',
        ),
    ]
